version: "3.7"
services:
  postgres:
    image: postgres:13.4
    container_name: postgresdb
    # Make postgres logs. More information about logging, see official documentation: https://www.postgresql.org/docs/11/runtime-config-logging.html
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    logging:
      options:
        max-size: "10k"
        max-file: "5"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sdmt
      POSTGRES_INIT_DB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
  # https://docs.localstack.cloud/get-started/

  memcached:
    image: memcached:1.6.6
    ports:
      - "11211:11211"

  localstack:
    container_name: localstack
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - TMPDIR=/private$TMPDIR
      - SERVICES=sqs,s3
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
