name: CI
on:
  push:
    paths-ignore:
      - '**/README.md'
      - 'docs/**'
      - 'front/**'
  pull_request:
    paths-ignore:
      - '**/README.md'
      - 'docs/**'
      - 'front/**'
jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    outputs:
      done: ${{ steps.check.outputs.message }}
    steps:
      - name: Chcek out
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build, test and coverage report
        run: sbt clean coverage test coverageAggregate
      - id: check
        if: ${{ always() }}
        run: |
          echo "::set-output name=message::Test A ${{ (job.status == 'success' && '✅') || '❌' }}"
          echo "- TestA : ${{ (job.status == 'success' && '✅') || '❌' }}" >> $GITHUB_STEP_SUMMARY
